name: video
description: A new Flutter project.
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1
environment:
  sdk: '>=3.0.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.2
  custom_navigation_bar: ^0.8.2
  google_nav_bar: ^5.0.6
  line_icons: ^2.0.3
  persistent_bottom_nav_bar_v2: ^4.2.8
  flutter_easyloading: ^3.0.5
  shared_preferences: ^2.2.0
  settings_ui: ^2.0.2
  provider: ^6.0.5
  banner_carousel: ^1.2.1
  google_fonts: ^5.1.0
  pull_to_refresh: ^2.0.0
  dio: ^4.0.4
  cached_network_image: ^3.2.1
  flutter_svg: ^1.1.6
  fluttertoast: ^8.0.7
  # 播放器
  video_player: ^2.7.0
  # 屏幕旋转
  auto_orientation: ^2.2.1
  # 亮度和音量调节
  brightness_volume: ^1.0.3
#  vimeo_video_player: ^0.0.6
  video_player_web_hls: ^1.1.0
  wakelock_plus: ^1.1.1
  #chewie: ^1.7.1
  #universal_html: ^2.2.4
dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_localizations:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true
  assets:
    - assets/
    - assets/images/
  fonts:
    - family: Zen Kaku Gothic New
      fonts:
        - asset: assets/fonts/ZenKakuGothicNewBold.ttf
          weight: 700
        - asset: assets/fonts/ZenKakuGothicNewMedium.ttf
          weight: 500
        - asset: assets/fonts/ZenKakuGothicNewRegular.ttf
          weight: 400
    - family: Inter
      fonts:
        - asset: assets/fonts/InterRegular.ttf
          weight: 400
    - family: Plus Jakarta Sans
      fonts:
        - asset: assets/fonts/PlusJakartaSansRegular.ttf
          weight: 400
        - asset: assets/fonts/PlusJakartaSansMedium.ttf
          weight: 500
flutter_intl:
  enabled: true
